services:
  filler:
    platform: linux/amd64
    build: .
    image: filler
    volumes:
      - ./solution:/filler/solution
    container_name: filler-bot
    stdin_open: true # interactive session open (-i)
    tty: true        # pseudo-TTY (-t)
