services:
  gridtactix:
    platform: linux/amd64
    build: .
    image: gridtactix
    volumes:
      - ./solution:/gridtactix/solution
    container_name: gridtactix-bot
    stdin_open: true # interactive session open (-i)
    tty: true        # pseudo-TTY (-t)
